# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b64f5fec0a38a7726b0c6e3a558ec7244f5574563addfa89a5762d94b5ed43e086542c40b8690e2844c5193b78e251970d632f11e038d71f8ca031b46a3512e2

test:
  secret_key_base: 94c25e573a45863dadf1d79b84d97d518193d7e531558c9cef807354cb549f77ad012784b99101a22dc09b7cd12a2dafb9019e0267a9da1bb3e649643bc0189f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
